RestClients:
  HANA_BUSINESS_PARTNER:
    UUID: 66c119a8-9209-4da5-814d-650f3c5a6c17
    Url: https://<your_sap_instance>/sap/opu/odata/SAP/API_BUSINESS_PARTNER
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - ch.ivyteam.ivy.rest.client.authentication.HttpBasicAuthenticationFeature
    Properties:
      JSON.Deserialization.FAIL_ON_UNKNOWN_PROPERTIES: 'false'
